version: '2'

# user: www-data
services:
   db:
     image: mysql:latest
     volumes:
        - ./db_data:/var/lib/mysql
     ports:
       - "3306:3306"
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=nextcloud
       - MYSQL_DATABASE=nextcloud
       - MYSQL_USER=nextcloud
       - MYSQL_PASSWORD=nextcloud
   web:
     # build and tag the current image based on php7.1-apache
     build: .
     image: mengqigu/nextcloud_web
     group_add:
       - www-data
     ports:
     #  Expose ports. Specify both ports (HOST:CONTAINER),
       - "8000:80"
       - "8001:443"
     volumes:
       - ./src:/var/www/nextcloud
