version: '2'

services:
   db:
     image: mysql:latest
     volumes:
        - ${DB_DATA_PATH}:/var/lib/mysql
     ports:
       - "3306:3306"
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=nextcloud
       - MYSQL_DATABASE=nextcloud
       - MYSQL_USER=nextcloud
       - MYSQL_PASSWORD=nextcloud
   web:
     # Image mengqigu/nextcloud_web is based on php7.1-apache's and
     # official nextcloud image's docker file
     build: .
     image: mengqigu/nextcloud_web
     user: root
     group_add:
       - www-data
     ports:
     #  Expose ports. Specify both ports (HOST:CONTAINER)
       - "8000:80"
       - "8001:443"
     volumes:
       - ${NEXTCLOUD_PATH}:/var/www/nextcloud
